name: python310
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - accelerate==0.34.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.11.0
      - anyio==4.9.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - axial-positional-embedding==0.3.12
      - bert-score==0.3.13
      - bleurt-pytorch==0.0.1
      - blis==1.3.0
      - cachetools==5.5.2
      - catalogue==2.0.10
      - certifi==2025.7.9
      - chardet==5.2.0
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpathlib==0.21.1
      - colorama==0.4.6
      - colt5-attention==0.11.1
      - confection==0.1.5
      - contourpy==1.3.2
      - cycler==0.12.1
      - cymem==2.0.11
      - dataproperty==1.1.0
      - datasets==4.0.0
      - decorator==5.2.1
      - dill==0.3.8
      - distro==1.9.0
      - einops==0.8.1
      - evaluate==0.4.5
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - filelock==3.13.1
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - genai==2.1.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.176.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.1
      - grpcio-status==1.71.2
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.33.2
      - hyper-connections==0.2.1
      - idna==3.10
      - ipdb==0.13.13
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - jiter==0.10.0
      - joblib==1.5.1
      - jsonlines==4.0.0
      - kiwisolver==1.4.8
      - langcodes==3.5.0
      - language-data==1.3.0
      - latex2sympy2-extended==1.10.2
      - lightning-utilities==0.15.2
      - llvmlite==0.44.0
      - lm-eval==0.4.9
      - local-attention==1.11.2
      - lxml==6.0.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - math-verify==0.8.0
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mbstrdecoder==1.1.4
      - mdurl==0.1.2
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - multidict==6.6.3
      - multiprocess==0.70.16
      - murmurhash==1.0.13
      - networkx==3.3
      - nltk==3.9.1
      - numba==0.61.2
      - numexpr==2.11.0
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - openai==0.27.10
      - packaging==25.0
      - pandas==2.3.1
      - parso==0.8.4
      - pathvalidate==3.3.1
      - peft==0.16.0
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.8
      - portalocker==3.2.0
      - preshed==3.0.10
      - product-key-memory==0.2.11
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybind11==3.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pytablewriter==1.2.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - reformer-pytorch==1.4.4
      - regex==2024.11.6
      - requests==2.32.4
      - rich==14.1.0
      - rouge-score==0.1.2
      - rsa==4.9.1
      - sacrebleu==2.5.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - selfcheckgpt==0.1.7
      - sentence-transformers==5.1.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.32.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.3.0.post1
      - smmap==5.0.2
      - sniffio==1.3.1
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlitedict==2.1.0
      - srsly==2.5.1
      - stack-data==0.6.3
      - sympy==1.13.1
      - tabledata==1.3.4
      - tabulate==0.9.0
      - tcolorpy==0.1.7
      - thinc==8.3.6
      - threadpoolctl==3.6.0
      - tiktoken==0.3.3
      - tokenizers==0.21.2
      - tomli==2.2.1
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchmetrics==1.8.0
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - tqdm-multiprocess==0.0.11
      - traitlets==5.14.3
      - transformers==4.53.2
      - transformers-stream-generator==0.0.5
      - triton==3.1.0
      - tslearn==0.6.4
      - typepy==1.3.4
      - typer==0.16.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - wandb==0.21.0
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - weasel==0.4.1
      - word2number==1.1
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.20.1
      - zstandard==0.23.0
prefix: /homes/55/yujunchi/ShenxuC/miniconda3/envs/python310
